config/routes.rb
Rails.application.routes.draw do
  
  namespace :api do
  namespace :v1 do
    get 'feed_items_controller/index'
    end
  end

  namespace :api do
  namespace :v1 do
    get 'feed_items_controller/create'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :students, :contracts, :activities, :feed_items
      
      namespace :accounts do
        post 'sign_in' => 'sessions#create', :as => 'sign_in'
        post 'sign_up' => 'users#create', as: 'sign_up'
        get 'edit' => 'users#edit', as: 'edit'
        get 'info' => 'users#show', as: 'info'
        put 'update' => 'users#update', as: 'update'
        delete 'delete' => 'users#delete', as: 'delete'
      end
    end
  end

  get 'home' => 'static_pages#home', :as => 'home'

  get 'learn' => 'static_pages#learn', :as => 'learn'

  get 'student_learn' => 'static_pages#student_learn', :as => 'student_learn'

  get 'sign_in' => 'static_pages#sign_in', :as => 'sign_in'

  get 'sign_up' => 'static_pages#sign_up', :as => 'sign_up'

  get 'sign_out' => 'static_pages#sign_out', :as => 'sign_out'

  get 'dashboard' => 'static_pages#dashboard', :as => 'dashboard'

  get 'student_dashboard' => 'static_pages#dashboard', :as => 'student_dashboard'

  get 'dashboard/:id' => 'static_pages#dashboard'

  get 'student_dashboard/:id' => 'static_pages#dashboard'

  get 'dashboard/add' => 'static_pages#dashboard'

  get 'dashboard/profile' => 'static_pages#dashboard'

  get 'dashboard/:id/create_contract' => 'static_pages#dashboard'

  root 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def learn
  end

  def student_learn
  end

  def sign_in
  end

  def sign_up
  end

  def sign_out
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<div class="header">
  <div class="header-content">
    <div class="header-logo">
      <%= 
	  link_to root_path do 
	    image_tag "logo.png"
	  end

	  %>
    </div>
    
    <div class="header-actions">
      <%= link_to "Login", "#" %> | <%= link_to "Sign up", "#" %>
    </div>
  </div>
</div>

<div class="content">
  <div class="content-content">
    <div class="promo-title">
      <h1>Inspire your child<br>to succeed</h1>
    </div>

    <div class="promo-text">
      <p>inspireDo gives you, as a parent, the tools to help your child on a path to sucess</p>
    </div>

    <div class="promo-sign-up">
      <%= link_to "Sign up now", "#", class: "button" %><br>
      <%= link_to "Learn more", learn_path, class: "button" %><br>
      <small><%= link_to "Not a parent?", student_learn_path %></small>
    </div>

    <div class="promo-image">
      <%= image_tag "iphone.png", class: "promo-image" %>
    </div>

  </div>
</div>

<div class="footer">

  <span class="contact">
    <small>Contact us at <%= link_to "erik@inspiredo.com", "mailto:erik@inspiredo.com" %></small>
  </span>
<div>

app/views/static_pages/learn.html.erb
<div class="header">
  <div class="header-content">
    <div class="header-logo">
      <%= 
	  link_to root_path do 
	    image_tag "logo.png"
	  end

	  %>
    </div>
    
    <div class="header-actions">
      <%= link_to "Login", "#" %> | <%= link_to "Sign up", "#" %>
    </div>
  </div>
</div>

<div class="content">
  <div class="content-content">
    <div class="promo-title">
      <h1>What is inspireDo?</h1>
    </div>

    <div class="promo-section">
      <div class="promo-section-title">
	<h2>Contracts</h2>
      </div>
      <div class="promo-section-text">
	<p>Contracts are composed of two things: activites and a reward. You specify how many points the student earns for each completion, and you specify how many points are needed to recieve the specified reward. Place a deadline on the contract to ensure regular completion.</p>
      </div>
    </div>

    <div class="promo-section">
      <%= image_tag "mac.png", class: "section-image" %>
      <div class="right">
	<div class="promo-section-title">
	  <h2>Tracking</h2>
	</div>
	<div class="promo-section-text">
	  <p>Checkin on their progress. See what they have recently completed. Make sure they are on track. You can see how much progress they have make toward the reward and how far they have to go.</p>
	</div>
      </div>
    </div>

    <div class="promo-section">
      <div class="promo-section-title">
	<h2>Contracts</h2>
      </div>
      <div class="promo-section-text">
	<p>Contracts are composed of two things: activites and a reward. You specify how many points the student earns for each completion, and you specify how many points are needed to recieve the specified reward. Place a deadline on the contract to ensure regular completion.</p>
      </div>
    </div>

    <div class="promo-sign-up">
      <%= link_to "Sign up now", "#", class: "button" %><br>
      <small><%= link_to "Not a parent?", student_learn_path %></small>
    </div>

    <div class="promo-image">

    </div>

  </div>
</div>

<div class="footer">

  <span class="contact">
    <small>Contact us at <%= link_to "erik@inspiredo.com", "mailto:erik@inspiredo.com" %></small>
  </span>
<div>

app/views/static_pages/student_learn.html.erb
<div class="header">
  <div class="header-content">
    <div class="header-logo">
      <%= 
	  link_to root_path do 
	    image_tag "logo.png"
	  end

	  %>
    </div>
    
    <div class="header-actions">
      <%= link_to "Login", "#" %> | <%= link_to "Sign up", "#" %>
    </div>
  </div>
</div>

<div class="content">
  <div class="content-content">
    <div class="promo-title">
      <h1>What About Students?</h1>
    </div>

    <div class="promo-section">
      <div class="promo-section-title">
	<h2></h2>
      </div>
      <div class="promo-section-text">
	<p>Currently, inspireDo requires that students have a mentor, so you need to be invited by a mentor. If you are interested though, click below to send an email to a person who you want to be your mentor.</p>
      </div>
    </div>

    
    <div class="promo-sign-up">
      <%= link_to "Send an Email", "mailto:?subject=Check Out inspireDo", class: "button" %><br>
     
    </div>

    <div class="promo-image">

    </div>

  </div>
</div>

<div class="footer">

  <span class="contact">
    <small>Contact us at <%= link_to "erik@inspiredo.com", "mailto:erik@inspiredo.com" %></small>
  </span>
<div>